import { Business, Customer, DashboardMetrics, Invoice, Payment, Quotation } from '@/types';

export const MOCK_BUSINESS: Business = {
  id: 'biz-1',
  name: 'Apex Electricals & Hardware',
  ownerName: 'Vikram Sharma',
  phone: '+91 98765 43210',
  email: 'vikram@apexelectricals.com',
  address: 'Plot 42, Industrial Area, Phase II, New Delhi',
  gstin: '07AAAAA0000A1Z5',
  currency: '₹',
};

export const MOCK_METRICS: DashboardMetrics = {
  totalSales: 184500,
  totalCollected: 142000,
  outstandingBalance: 42500,
  overdueAmount: 12000,
  activeQuotationsCount: 5,
  pendingInvoicesCount: 4,
  customersCount: 18,
};

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    businessId: 'biz-1',
    name: 'Raj Traders & Supplies',
    phone: '+91 98111 22334',
    email: 'raj@rajtraders.in',
    address: 'Shop 14, Main Market, Rohini Sector 7, Delhi',
    gstin: '07BBBBB1111B1Z2',
    notes: 'Preferred payment via UPI. Bulk purchaser for commercial PVC pipes.',
    totalBilled: 64000,
    outstandingBalance: 6800,
  },
  {
    id: 'cust-2',
    businessId: 'biz-1',
    name: 'Metro Heights Infrastructure',
    phone: '+91 99222 33445',
    email: 'accounts@metroheights.co.in',
    address: 'Tower B, Cyber Park, Gurugram, Haryana',
    gstin: '06CCCCC2222C1Z3',
    notes: 'Large commercial project. Invoices require 15-day clearance window.',
    totalBilled: 120500,
    outstandingBalance: 35700,
  },
  {
    id: 'cust-3',
    businessId: 'biz-1',
    name: 'Sharma Fabrications',
    phone: '+91 97333 44556',
    email: 'sharma.fab@gmail.com',
    address: 'Gala 3, Steel Market, Faridabad, Haryana',
    totalBilled: 32000,
    outstandingBalance: 0,
  },
];

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'qt-1',
    businessId: 'biz-1',
    customerId: 'cust-1',
    customerName: 'Raj Traders & Supplies',
    quotationNumber: 'QT-2026-0012',
    issueDate: '2026-09-15',
    validUntil: '2026-09-30',
    status: 'SENT',
    subtotal: 10000,
    discount: 0,
    tax: 1800,
    total: 11800,
    notes: 'Price valid until 30th Sep 2026. Delivery included in municipal limits.',
    items: [
      {
        id: 'qti-1',
        quotationId: 'qt-1',
        description: '2-inch Heavy Duty PVC Conduit Pipes (6m length)',
        quantity: 20,
        unitPrice: 500,
        taxRate: 18,
        taxAmount: 1800,
        lineTotal: 11800,
      },
    ],
  },
  {
    id: 'qt-2',
    businessId: 'biz-1',
    customerId: 'cust-2',
    customerName: 'Metro Heights Infrastructure',
    quotationNumber: 'QT-2026-0013',
    issueDate: '2026-09-18',
    validUntil: '2026-10-05',
    status: 'ACCEPTED',
    subtotal: 45000,
    discount: 2500,
    tax: 7650,
    total: 50150,
    notes: 'Commercial rate bundle. Awaiting PO conversion.',
    items: [
      {
        id: 'qti-2',
        quotationId: 'qt-2',
        description: 'Industrial 3-Phase Copper Armoured Cable (100m)',
        quantity: 2,
        unitPrice: 22500,
        taxRate: 18,
        taxAmount: 7650,
        lineTotal: 50150,
      },
    ],
  },
  {
    id: 'qt-3',
    businessId: 'biz-1',
    customerId: 'cust-3',
    customerName: 'Sharma Fabrications',
    quotationNumber: 'QT-2026-0011',
    issueDate: '2026-09-10',
    validUntil: '2026-09-24',
    status: 'DRAFT',
    subtotal: 15400,
    discount: 0,
    tax: 2772,
    total: 18172,
    items: [
      {
        id: 'qti-3',
        quotationId: 'qt-3',
        description: 'Welding Rods & Consumables Pack',
        quantity: 14,
        unitPrice: 1100,
        taxRate: 18,
        taxAmount: 2772,
        lineTotal: 18172,
      },
    ],
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    businessId: 'biz-1',
    customerId: 'cust-1',
    customerName: 'Raj Traders & Supplies',
    quotationId: 'qt-1',
    invoiceNumber: 'INV-2026-0042',
    issueDate: '2026-09-10',
    dueDate: '2026-09-25',
    subtotal: 10000,
    discount: 0,
    tax: 1800,
    total: 11800,
    paidAmount: 5000,
    status: 'PARTIALLY_PAID',
    items: [
      {
        id: 'ii-1',
        invoiceId: 'inv-1',
        description: '2-inch Heavy Duty PVC Conduit Pipes (20 pcs)',
        quantity: 20,
        unitPrice: 500,
        taxRate: 18,
        taxAmount: 1800,
        lineTotal: 11800,
      },
    ],
  },
  {
    id: 'inv-2',
    businessId: 'biz-1',
    customerId: 'cust-2',
    customerName: 'Metro Heights Infrastructure',
    invoiceNumber: 'INV-2026-0038',
    issueDate: '2026-08-20',
    dueDate: '2026-09-05',
    subtotal: 30000,
    discount: 0,
    tax: 5400,
    total: 35400,
    paidAmount: 0,
    status: 'OVERDUE',
    items: [
      {
        id: 'ii-2',
        invoiceId: 'inv-2',
        description: 'Sub-Station Switchgear Installation Service',
        quantity: 1,
        unitPrice: 30000,
        taxRate: 18,
        taxAmount: 5400,
        lineTotal: 35400,
      },
    ],
  },
  {
    id: 'inv-3',
    businessId: 'biz-1',
    customerId: 'cust-3',
    customerName: 'Sharma Fabrications',
    invoiceNumber: 'INV-2026-0035',
    issueDate: '2026-08-15',
    dueDate: '2026-08-30',
    subtotal: 20000,
    discount: 1000,
    tax: 3420,
    total: 22420,
    paidAmount: 22420,
    status: 'PAID',
    items: [
      {
        id: 'ii-3',
        invoiceId: 'inv-3',
        description: 'Sheet Metal & Structural Channel Work',
        quantity: 1,
        unitPrice: 20000,
        taxRate: 18,
        taxAmount: 3420,
        lineTotal: 22420,
      },
    ],
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    invoiceId: 'inv-1',
    invoiceNumber: 'INV-2026-0042',
    customerName: 'Raj Traders & Supplies',
    amount: 5000,
    paymentDate: '2026-09-12',
    method: 'UPI',
    reference: 'UPI/260912/88219',
    notes: 'Advance installment received via GooglePay.',
  },
  {
    id: 'pay-2',
    invoiceId: 'inv-3',
    invoiceNumber: 'INV-2026-0035',
    customerName: 'Sharma Fabrications',
    amount: 22420,
    paymentDate: '2026-08-28',
    method: 'BANK_TRANSFER',
    reference: 'NEFT-HDFC-9921820',
    notes: 'Full settlement received on invoice due.',
  },
];
