"""add unique constraint on business invoice number

Revision ID: 793ae401aa60
Revises: efa00dc9b333
Create Date: 2026-09-20 20:04:17.772537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793ae401aa60'
down_revision: Union[str, Sequence[str], None] = 'efa00dc9b333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_business_invoice_number', 'invoices', ['business_id', 'invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_invoice_number', 'invoices', type_='unique')
    # ### end Alembic commands ###
