"""create invoice reminders table

Revision ID: d9d81790d702
Revises: 54592bc72639
Create Date: 2026-09-20 18:39:38.680502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d81790d702'
down_revision: Union[str, Sequence[str], None] = '54592bc72639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_reminders',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'SMS', 'SHARE', 'EMAIL', name='reminder_channel_enum'), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_reminders_business_id'), 'invoice_reminders', ['business_id'], unique=False)
    op.create_index(op.f('ix_invoice_reminders_id'), 'invoice_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_reminders_invoice_id'), 'invoice_reminders', ['invoice_id'], unique=False)
    op.add_column('invoices', sa.Column('last_reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'last_reminded_at')
    op.drop_index(op.f('ix_invoice_reminders_invoice_id'), table_name='invoice_reminders')
    op.drop_index(op.f('ix_invoice_reminders_id'), table_name='invoice_reminders')
    op.drop_index(op.f('ix_invoice_reminders_business_id'), table_name='invoice_reminders')
    op.drop_table('invoice_reminders')
    # ### end Alembic commands ###
