"""add document settings to businesses

Revision ID: efa00dc9b333
Revises: d9d81790d702
Create Date: 2026-09-20 19:08:03.532318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa00dc9b333'
down_revision: Union[str, Sequence[str], None] = 'd9d81790d702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('invoice_prefix', sa.String(length=20), server_default='INV', nullable=False))
    op.add_column('businesses', sa.Column('quotation_prefix', sa.String(length=20), server_default='QT', nullable=False))
    op.add_column('businesses', sa.Column('default_terms', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('payment_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'payment_instructions')
    op.drop_column('businesses', 'default_terms')
    op.drop_column('businesses', 'quotation_prefix')
    op.drop_column('businesses', 'invoice_prefix')
    # ### end Alembic commands ###
